sudo: false
dist: trusty
language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: oraclejdk10
      env: JDK_RELEASE='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

#before_script:
#    - wget http://services.gradle.org/distributions/gradle-4.6-bin.zip
#    - unzip gradle-4.6-bin.zip
#    - export GRADLE_HOME=$PWD/gradle-4.6
#    - export PATH=$GRADLE_HOME/bin:$PATH
